# Uncomment this line to define a global platform for your project
platform :ios, '14.0'

# CocoaPods analytics sends network stats synchronously affecting build performance.
ENV['COCOAPODS_DISABLE_STATS'] = '1'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('Flutter', 'Generated.xcconfig'), File.dirname(__FILE__))
  unless File.exist?(generated_xcode_build_settings_path)
    raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get has been executed."
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    if line =~ /FLUTTER_ROOT=(.*)/
      return $1.strip
    end
  end
  raise "FLUTTER_ROOT not found in Generated.xcconfig."
end

podhelper_path = File.expand_path(File.join('Flutter', 'podhelper.rb'), File.dirname(__FILE__))
if File.exist?(podhelper_path)
  require podhelper_path
else
  require File.expand_path('packages/flutter_tools/bin/podhelper.rb', flutter_root)
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!

  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|
      # Force deployment target to 14.0 for all pods
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '14.0'
    end
  end
end
