name: Prepare iOS Widget Files
on: workflow_dispatch

jobs:
  modify-project:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4

      - name: Install xcodeproj
        run: gem install xcodeproj

      - name: Run Ruby Script
        run: ruby setup_widget.rb

      - name: Archive Project Files
        run: |
          if [ -d "ios/WidgetExtension" ]; then
            echo "Environment prepared."
          fi
          zip -r ios_updated.zip ios/

      - name: Upload Updated iOS Folder
        uses: actions/upload-artifact@v4
        with:
          name: updated-ios-project
          path: ios_updated.zip
